# Generated by Django 4.1.3 on 2022-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('1', 'Unit1'), ('2', 'Unit2'), ('3', 'Unit3'), ('4', 'Unit4')], default='1', max_length=1)),
                ('hmwname', models.CharField(max_length=120)),
                ('githubrepo', models.CharField(max_length=120)),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
    ]
