# Generated by Django 4.1.3 on 2022-12-04 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='deliverable',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='deliverable date'),
            preserve_default=False,
        ),
    ]
